git:
  depth: 3
language: node_js
node_js: stable
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: gQ8LvILn7eEPCmJYSLNo/XrnwWxIp7t4pOd+XHx7x1gYUb5LpCgr7NuMVCWIhV06QZmAxtlKxRI9uyYFVEv6Qfl6We9SNq2cf3i3l9ttgS/nwTIboi/uzlrVxZglDhEiv26t+uJ3BRC5+y7bLUfgsHGAARBn9ie1GOP87zwsJAQ1V64fVFjwWaPRtzk1UK8Om3Qp7j+f1sARA2ZZ3LTkyuU89ZvSJhxaPuIe5B6eVDRJ9Q7zPUG4lWQyDw5W9h6uIjQ1eBU4Se1XRA+BpE29EWQVVUCiCA1eDidOJPrcNx8VDZIO2jNtcvSeteaXeXSCNe3/CnzQ/hQy+4lbj7BLX7gghtFGMM0HhqXiAjG+zQoShL2Qgw1HoD46cWkqxaEKGjRNMYc5hOAdYda+4o2Lyx3TutisWEABjiBafpPnOD33IbzEZ5fz+Xtzf0IHmnJS1eGZBKATlP7qVZUlgkZjud2xoCl5F9qYih0pOAZoFcFzr5SO3nS3A1TuUgVNGju/Y5UxUbIWS2rWdF3k5eArm5rksXqY9ZF6wPt4Y8/qLl+Dy4E2mafhbfef2ONXMdv+Mv9gtjH0j/EZ/IqKuHuxiX1RCRAnnoZpTVUNJ/dTDkoBg+FRDHdP6IhqV1yWr+jah2y1cyWu3P4k1cJXaUkf5KiUJBnNb7GHtxuXPToRh+U=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- git config --global user.name "Avi Sharvit"
- git config --global user.email sharvita@gmail.com
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
after_success:
- if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ]; then echo "Deployments are only done for
  the version tags. Current branch is $TRAVIS_BRANCH"; exit 0; fi
- echo "Deploying build $TRAVIS_BUILD_NUMBER - $TRAVIS_TAG"
- gulp deploy:gh-pages
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: ZZu4Tw4QOBZyN3kmK8OxVM+tMg3GbRtqoceuAlj8HmRxRL2LzQR3oQLsPvvwEBcrZH6MG2mQAEzWyjkkZPhwjvCwAhemGrlX1wSzEQQlnjsaxRXEAnsV7bHT2damtmi8JE4z8y6ldTRRsu+UNr5n7Kuo754wJGhzAqnxkL1GXyPCmT2iIHc3Xfz9I9T7HgTYhrEYVGNJO2umd8AXn/B9uSaxia6xpBRTlnueTqQ/BjVLfw9aLbezP0ZoFtecKdsW9tLPGl8wHs7Rb/iYWQu47eqkyPpHNYWjXuw5oNOxEs1QErtRkCXRNOQI9uFDzjFFIdzbPlQgHAP2B/nYAdqS2eIeo0x2MH1K/nv7I9msTf+GrOX0fYftQYf7OM1k2rlvbxYYB5K3x4M7nbbUYMlQXXXlhZ2ydKRXlR4sy0ekbqtOF1ewz5qnK2DiudvRajvqtcySz///lu2EgHW+9JUotKnqsypsl8b1xCNeeQbyLGKCPfqiX14WWISCTlkfzTL6x92NJD6tP9/NWZtQOs+VSU5bPAqY72TGJWbszb9LItfY3JDC0a0iVpugI/TLgsFd9roLVZa167kx5BaTLlZpuOoiFuKQ6eOJioJCgHxSi6EzNKMkAOMlamrIWzEx3DSEMVfu6pVm3ZqnnL+v29D3Az9Y8i5pzIcF9w484SscFYY=
  on:
    tags: true
    repo: sharvit/angular-bootstrap-locale-dialog
- provider: npm
  skip_cleanup: true
  email: sharvita@gmail.com
  api_key:
    secure: GaCzA/GIAkqyyS+mzV9DC9irWv+4PxnphKClM7jV+TpuitPOZG0rPTk5uLzd4pCcU6haQHxHkqmwAUnox+YWMR7ugPnKEp0K3Znkgxc7s6mOY2OnbfF8+8UbNHp11eNkOnSmK5zUTOY9v0GNO8RshOnrGm5JD6ITThWZGTgXHAiZ3xh2+Tcwe6MvxOZBLVRuOrfD57Eqkb7HhZERRj10VJyGXAfrgvE41Dh8sV0Xz51xzukj/tHGdYEI+z9Bmf1CcXej2Hv0r6MJqzBTrwDA09C95N752Z1sM0w0Qd8zqm5WXNMxH9WXXOarSomE/eKGkkNix8LtELepetRGWySv3MdhKx3SxVpILUuoIBVL1p/5Oo+FtQT83fVHowe9rn9oXRpzm3gIg0M/27FfAHjptKEGt3byZA47I4wIx090bj9ZysaflbdTqzXoFyquoAjrDvu13bCZL4fD8fiDgRxzBt9CSfJDdkUDTzul+a5LacQ3xmi7lPuaBWiuycfazVTV03jNsJT5SCcRFkol4jIb9CzSh+IO6tuiY8Eli5D63J9xTr6oLKBuiyxwQsWxT7PEJCuwTsyH0eCJuztHaZXz1eqmLEdKPge72qM4hIuh5JtC3978G5n1AQEYfbG1MkpA0JeMlnPT/Ma6ee3H0kFrDaQvXEM9/pu2K3b8wEN82I4=
  on:
    tags: true
    repo: sharvit/angular-bootstrap-locale-dialog
